export const RETAINED_BLOCK_TYPES = [
  "paragraph",
  "heading",
  "hardBreak",
  "blockquote",
  "bulletList",
  "orderedList",
  "listItem",
  "tableBlock",
  "table",
  "tableRow",
  "tableHeader",
  "tableCell",
  "horizontalRule",
  "callout",
  "image",
  "video",
  "audio",
  "embed",
  "fileAttachment",
  "reference",
  "codeBlock",
  "diagram",
  "mathBlock",
  "mathInline",
  "glossaryTerm",
  "steps",
  "step",
  "poll",
  "questionPool",
] as const

export const RETAINED_MARK_TYPES = [
  "bold",
  "italic",
  "strike",
  "code",
  "underline",
  "link",
  "highlight",
  "textStyle",
] as const

export const CURSARE_DIRECTIVES = {
  containers: ["callout", "table", "steps", "step"],
  atomic: [
    "image",
    "video",
    "audio",
    "file",
    "embed",
    "diagram",
    "math",
    "poll",
    "quiz",
    "reference",
  ],
  inline: ["glossary", "math-inline", "underline", "highlight", "color"],
} as const
